In [1]:
import pandas as pd

In [2]:
data_path1 = "data/transcript_expression_liver.csv"
data_path2 = "data/mrna_half-life.csv"
data_path3 = "data/protein_expression_5class.csv"
data_path4 = "data/translation_rate.csv"

In [3]:
df_demo1 = pd.read_csv(data_path1)
df_demo2 = pd.read_csv(data_path2)
df_demo3 = pd.read_csv(data_path3)
df_demo4 = pd.read_csv(data_path4)

In [4]:
df_demo3.head()

,Gene ID,Transcript ID,5' UTR,CDS,3' UTR,split,Classification,ClassificationID
0,ENSG00000155657,ENST00000589042,GAGCAGTCGTGCATTCCCAGCCTCGCCTCGGGTGTAGGGATTGCAT...,ATGACAACTCAAGCACCGACGTTTACGCAGCCGTTACAAAGCGTTG...,GAGGGCCTGTGCCCTTATACTCTACACTCATTCTTAACTTTTCGCA...,1,Tissue enriched,3
1,ENSG00000181143,ENST00000397910,AAGCGTTGCACAATTCCCCCAACCTCCATACATACGGCAGCTCTTC...,ATGCTGAAACCCTCAGGCCTTCCTGGGTCATCTTCTCCCACCCGCT...,CTGGAACTTGCCGGTGCCTGGGGTGCCTTTCCCCCAGCCAGGGTCC...,1,Tissue enriched,3
2,ENSG00000175387,ENST00000262160,CCGCGCGCCCGGGCCGCCGGCCGGGCCCGGGCCTGGGGGCGGGGCG...,ATGTCGTCCATCTTGCCATTCACGCCGCCAGTTGTGAAGAGACTGC...,AGCTTCACCAATCAAGTCCCATGAAAAGACTTAATGTAACAACTCT...,5,Expressed in all,1
3,ENSG00000185070,ENST00000330753,AGTTGTACGTTCGAAACCTGTCGCCGTCACTTGCGCGTTTGGCATT...,ATGGGCCTACAGACCACAAAGTGGCCCAGCCATGGGGCTTTTTTCC...,CAGCCAGAGGCCCAGCGTTATCAAGGCGGACAATTAGACTCTTGAG...,5,Tissue enriched,3
4,ENSG00000273079,ENST00000609686,CCCTTAGGAAGGGGACGCTTTGGGAATGACCATGCTCCACCGAGGG...,ATGAAGCCCAGAGCGGAGTGCTGTTCTCCCAAGTTCTGGTTGGTGT...,GTGAGGGAACAGAGAGGTTAAGGTGGGTACGGGAGGGTAAGGCTGT...,4,Group enriched,0

In [15]:
df_demo1.head()

,Gene ID,Transcript ID,5' UTR,CDS,3' UTR,split,y
0,ENSG00000166710,ENST00000561424,TGGCGGGCATTCCTGAAGCTGACAGCATTCGGGCCGAG,ATGTCTCGCTCCGTGGCCTTAGCTGTGCTCGCGCTACTCTCTCTTT...,GCAGCATCATGGAGGTTTGAAGATGCCGCATTTGGATTGGATGAAT...,5,1768.9500
1,ENSG00000133112,ENST00000379060,GTTTCAGGCTCGTGCTAAGCTAGCGCCGTCGTCGTCTCCCTTCAGT...,ATGTTCTCCGACATCTACAAGATCCGGGAGATCGCGGACGGGTTGT...,CAAATGTGGCAATTATTTTGGATCTATCACCTGTCATCATAACTGG...,3,1691.4800
2,ENSG00000075624,ENST00000331789,GAGTGAGCGGCGCGGGGCCAATCAGCGTGCGCCGTTCCGAAAGTTG...,ATGGATGATGATATCGCCGCGCTCGTCGTCGACAACGGCTCCGGCA...,GCGGACTATGACTTAGTTGCGTTACACCCTTTCTTGACAAAACCTA...,5,376.6500
3,ENSG00000090382,ENST00000261267,GTTAAAAGATGTTAAATACTGGGGCCAGCTCACCCTGGTCAGCCTA...,ATGAAGGCTCTCATTGTTCTGGGGCTTGTCCTCCTTTCTGTTACGG...,CTCCAGAATTTTCCTTCTTCAGCTCATTTTGTCTCTCTCACATTAA...,3,93.3402
4,ENSG00000166710,ENST00000544417,AATATAAGTGGAGGCGTCGCGCTGGCGGGCATTCCTGAAGCTGACA...,ATGTCTCGCTCCGTGGCCTTAGCTGTGCTCGCGCTACTCTCTCTTT...,GCAGCATCATGGAGGTTTGAAGATGCCGCATTTGGATTGGATGAAT...,1,864.8790

In [16]:
set(df_demo1['split'])

{1, 2, 3, 4, 5}

In [17]:
df_demo2.head()

,UTR5,CDS,UTR3,y,split
0,GGCTTTGGCCCTGGAAAGCCTCGCGGACGTGTTCTGACCCAAGGTT...,ATGTTTTTACCTCATATGAACCACCTGACATTGGAACAGACTTTCT...,AACTTATCACTAGGCAGAACTGGGTTTGATGCTTTGTCAACTGAAA...,0.090027,0
1,GACCTACCGACCATTCTTCCGGGTCCAGAAGGTGATCTCCGCCCGT...,ATGAACCAGAAGCTACTGAAGTTGGAGAACTTGCTACGATTTCACA...,AATTACATTAAAAATGTAAATAACTCAACGTGTTGTTTGTTTGAAG...,0.493896,0
2,TAGATCGTCAGGAAAAGCCTAAAGATTAGACTGTAAGAAAAGAAAA...,ATGTTTCGAAGACCTGTATTACAGGTACTTCGTCAGTTTGTAAGAC...,AAAGGATGATTCTTCTTTGGCCATCATTTGGGATTCTGACACAGCC...,1.508789,0
3,TTCTGTGAACATTTGGAATTCTGTATTCAAAATCTATTTTGACCAT...,ATGTCGGAGCCCCACAGGGTCCAGTTCACCTCTCTCCCAGGTTCCC...,CCGCTTCAGAGGCAAGGCTTGCCACTTGGGTCTGGGTGGAATCAGA...,-0.536133,0
4,GATTCCCCTTTGTTCGGGTTCGCCATTTTGCTAGGCAGCGGCAGTG...,ATGGAGCAGTATACAGCAAACAGCAATAGTTCGACAGAGCAGATTG...,CCCCACGCCATGTGATGGAGCTGATCAAGGTCATGTTTCTCACTGT...,-1.348633,0

In [18]:
set(df_demo2['split'])

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [19]:
df_demo3.head()

,Gene ID,Transcript ID,5' UTR,CDS,3' UTR,split,Classification,ClassificationID
0,ENSG00000155657,ENST00000589042,GAGCAGTCGTGCATTCCCAGCCTCGCCTCGGGTGTAGGGATTGCAT...,ATGACAACTCAAGCACCGACGTTTACGCAGCCGTTACAAAGCGTTG...,GAGGGCCTGTGCCCTTATACTCTACACTCATTCTTAACTTTTCGCA...,1,Tissue enriched,3
1,ENSG00000181143,ENST00000397910,AAGCGTTGCACAATTCCCCCAACCTCCATACATACGGCAGCTCTTC...,ATGCTGAAACCCTCAGGCCTTCCTGGGTCATCTTCTCCCACCCGCT...,CTGGAACTTGCCGGTGCCTGGGGTGCCTTTCCCCCAGCCAGGGTCC...,1,Tissue enriched,3
2,ENSG00000175387,ENST00000262160,CCGCGCGCCCGGGCCGCCGGCCGGGCCCGGGCCTGGGGGCGGGGCG...,ATGTCGTCCATCTTGCCATTCACGCCGCCAGTTGTGAAGAGACTGC...,AGCTTCACCAATCAAGTCCCATGAAAAGACTTAATGTAACAACTCT...,5,Expressed in all,1
3,ENSG00000185070,ENST00000330753,AGTTGTACGTTCGAAACCTGTCGCCGTCACTTGCGCGTTTGGCATT...,ATGGGCCTACAGACCACAAAGTGGCCCAGCCATGGGGCTTTTTTCC...,CAGCCAGAGGCCCAGCGTTATCAAGGCGGACAATTAGACTCTTGAG...,5,Tissue enriched,3
4,ENSG00000273079,ENST00000609686,CCCTTAGGAAGGGGACGCTTTGGGAATGACCATGCTCCACCGAGGG...,ATGAAGCCCAGAGCGGAGTGCTGTTCTCCCAAGTTCTGGTTGGTGT...,GTGAGGGAACAGAGAGGTTAAGGTGGGTACGGGAGGGTAAGGCTGT...,4,Group enriched,0

In [20]:
set(df_demo3['split'])

{1, 2, 3, 4, 5}

In [4]:
df_demo4.head()

,ID,ENSTID,CDS,UTR5,UTR3,y,split
0,ENSG00000157514,ENST00000372383,ATGGCCCAGTCCAAGCTCGATTGCCGCTCACCTGTCGGCCTCGACT...,ctccacaggtccgccccaatccccgctcacacttgggaaacttggg...,gtggctctgtcctcagggtgggcagagccactaaacttgttttacc...,1.180393,4
1,ENSG00000169567,ENST00000506908,ATGGCAGATGAGATTGCCAAGGCTCAGGTCGCTCGGCCTGGTGGCG...,acgcgcaagattaggtggggcgccagagccggggcacctgcgcagg...,tttattttcttgctttttaaattgtgagattaattttgtccttaaa...,-0.121110,3
2,ENSG00000184014,ENST00000679999,ATGAGTGGCGGCGGCGGCGGAGGGGGCTCGGCGCCCAGTCGCTTCG...,ggtctcggccccggcgcc,agtcttgtagagtgtgtgcctcagctagttggagatggagcagact...,-1.842152,5
3,ENSG00000156011,ENST00000327040,ATGGAAGGAAGGAGCGCAGCGGCAGAGACATTTGTTTGGGTGAACA...,ggcagtcccgggagctcaacaaagagcacgcggcgctggccgccgg...,agtccatctgcggccaggaagtgctggtcatggagcaaaatagggt...,-1.284636,3
4,ENSG00000126261,ENST00000246548,ATGGCACTGTCGCGGGGGCTGCCCCGGGAGCTGGCTGAGGCGGTGG...,gcggctcggttctcccgcctccgcctccgccgcggctcgtggttgt...,acagaaatgcctctaaacagaaccctcttactatttagtttatctg...,0.046387,2